services:
  app:
    image: louislam/uptime-kuma:1.23.15-debian
    container_name: uptime
    restart: unless-stopped
    networks:
      - public
    env_file:
      - ./app.env
    volumes:
      - ./data:/app/data

networks:
  public:
    external: true

