services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.13-debian
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - public
    env_file:
      - ./app.env
    volumes:
      - data:/app/data

networks:
  public:
    external: true

volumes:
  data:

