services:
  app:
    container_name: uptime
    image: louislam/uptime-kuma:1.23.16-debian
    restart: unless-stopped
    networks:
      - default
    env_file:
      - ./app.env
    volumes:
      - ./data:/app/data

networks:
  public:
    name: web
    external: true

