services:
  app:
    image: louislam/uptime-kuma:1.23.15-debian
    networks:
      - public
    environment:
      - PUID=65534
      - PGID=65534
    volumes:
      - data:/app/data

networks:
  public:
    external: true

volumes:
  data:

