services:
  pastey:
    image: louislam/uptime-kuma:1.23.13-debian
    container_name: uptime-kuma
    restart: unless-stopped
    user: nobody:nogroup
    networks:
      - web
    env_file:
      - ./app.env
    volumes:
      - ./data:/app/data

networks:
  web:
    external: true

